export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';

export const GET_PRODUCT = 'GET_PRODUCT';

export const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES';

export const DELETE_PRODUCT = 'DELETE_PRODUCT';

export const POST_PRODUCT = 'POST_PRODUCT';

export const PUT_PRODUCT = 'PUT_PRODUCT';


