export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';

export const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES';

export const DELETE_PRODUCT = 'DELETE_PRODUCT';

export const GET_CATEGORY_FILTER = 'GET_CATEGORY_FILTER';

export const POST_PRODUCT = 'POST_PRODUCT';

export const GET_PRODUCT_BY_ID = 'GET_PRODUCT_BY_ID';

export const GET_PRODUCT_BY_NAME = 'GET_PRODUCT_BY_NAME';

export const PUT_PRODUCT = 'PUT_PRODUCT';